Repository DO-SOPT-Seminar-Web-6/Client, pull requests merged in 2023-12, with the labels that each got.

#65 Design#36 directrot/UI
  src/components/common/Button/Button.tsx
  src/components/common/MovieArticle/MovieArticle.tsx
  src/components/director/directorDetail/DirectorDetail.tsx
  src/components/director/directorDetail/DirectorInfo.tsx
  src/components/director/directorDetail/DirectorLike.tsx
  src/components/director/directorDetail/DirectorSubInfo.tsx
  src/components/director/directorFilmo/DirectorFilmo.tsx
  src/components/director/directorFilmo/FilmoContainer.tsx
  src/components/director/directorFilmo/FilmoTable.tsx
  src/core/ directorMovies.ts
  src/hooks/useShowMore.tsx
  src/pages/Director/Director.tsx
  src/styles/common/Dummy.tsx
  src/styles/theme.ts
Labels: ✨ feature, 💄 design, ♻️ refactor

#67 Feat#60 myPageCast get
  src/api/getMyPageProduction.ts
  src/components/cast/CastArticle.tsx
  src/components/cast/CastInfo.tsx
  src/components/cast/CastSection.tsx
  src/hooks/useGetMyPageProduction.ts
  src/types/dataTypes.ts
  src/utils/MyPageModal.tsx
Labels: ✨ feature

#69 Feat#62 main star
  src/components/myPage/SetStars.tsx
Labels: ✨ feature, 💄 design

#70 Feat#68 myPageComment get
  src/api/getMyPageComment.ts
  src/components/myPage/MyPagePopularComment.tsx
  src/components/myPage/PopularCommentBottom.tsx
  src/components/myPage/PopularCommentDetails.tsx
  src/components/myPage/PopularCommentHeader.tsx
  src/hooks/useGetMyPageComment.ts
  src/styles/common/commonIcon.ts
  src/types/commentDataTypes.ts
Labels: ✨ feature

#72 Feat#66 comment/api
  src/api/customAxios.ts
  src/api/getAnimationCollection.ts
  src/api/getComment.ts
  src/api/postCollectionAnimation.ts
  src/components/cast/Cast.tsx
  src/components/comments/CommentHeader.tsx
  src/components/comments/CommentSection.tsx
  src/components/comments/CommentToggle.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/CommentBottom.tsx
  src/components/common/Comment/CommentTop.tsx
  src/components/mainComment/MainComment.tsx
  src/components/mainComment/MainCommentDetail.tsx
  src/components/similar/Similar.tsx
  src/hooks/useGetComment.ts
  src/pages/Comment.tsx
Labels: ✨ feature

#75 Hotfix#73 comment layout
  src/components/comments/CommentHeader.tsx
  src/components/comments/CommentSection.tsx
  src/components/comments/CommentToggle.tsx
  src/components/director/directorFilmo/FilmoContainer.tsx
Labels: 🐛 hotfix, 💄 design

#81 [ refactor ] 댓글 수순, 좋아요 순 정렬 잘 되도록 수정
  src/components/comments/CommentSection.tsx
  src/hooks/useGetComment.ts
Labels: 🐛 hotfix, ♻️ refactor

#79 Feat#76 MyPage/navigate
  src/components/cast/Cast.tsx
  src/components/cast/CastArticle.tsx
  src/components/cast/CastHeader.tsx
  src/components/collection/CollectionArticle.tsx
  src/components/mainComment/MainCommentHeader.tsx
  src/utils/MyPageToggle.tsx
Labels: ✨ feature

#83 HotFix#76 MyPage/Navigate
  src/components/collection/CollectionArticle.tsx
  src/pages/Animation.tsx
Labels: 🐛 hotfix
