Repository DO-SOPT-Seminar-Web-6/Client, pull requests merged in 2023-11, with the labels that each got.

#2 Feat#1 layout/header
  package.json
  src/App.tsx
  src/assets/index.ts
  src/components/layout/Footer/Footer.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderLeft/HeaderLeft.tsx
  src/components/layout/Header/HeaderLeft/HeaderNav.tsx
  src/components/layout/Header/HeaderRight/HeaderInput.tsx
  src/components/layout/Header/HeaderRight/HeaderRight.tsx
  src/styles/globalStyle.ts
  src/styles/layout/Header/Header.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 💄design

#11 Design#8 animation/header
  src/App.tsx
  src/assets/index.ts
  src/components/animation/AnimationHeader.tsx
  src/components/animation/AnimationTitle.tsx
  src/components/animation/AnimationTitleButtons.tsx
  src/components/animation/AnimationTitleDetail.tsx
  src/components/animation/AnimationTitleHeader.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/MovieArticle/MovieInfo.tsx
  src/components/layout/Footer/FooterBottom/FooterBottomSecondRow.tsx
  src/components/layout/Footer/FooterTop.tsx
  src/components/layout/Header/HeaderLeft/HeaderLeft.tsx
  src/components/layout/Header/HeaderRight/HeaderInput.tsx
  src/components/layout/Header/HeaderRight/HeaderRight.tsx
  src/pages/Animation.tsx
Labels: 💄design

#13 Design#5-main/components
  .eslintrc.js
  .stylelintrc.json
  src/App.tsx
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/CommentBottom.tsx
  src/components/common/Comment/CommentTop.tsx
Labels: 💄design

#23 Feat#22-main/router
  src/App.tsx
  src/Router.tsx
  src/components/layout/MainLayout.tsx
  src/pages/Animation/Animation.tsx
  src/pages/Comments/Comments.tsx
  src/pages/Director/Director.tsx
  src/pages/Dummy.tsx
  src/pages/Error/Error.tsx
  src/pages/Main/Main.tsx
Labels: ✨ feature

#14 Design#12 main/thumnail
  src/App.tsx
  src/components/thumbnail/Thumbnail.tsx
  src/components/thumbnail/ThumbnailHeader.tsx
  src/components/thumbnail/ThumbnailTitle.tsx
  src/components/thumbnail/ThumbnailTitleDescription.tsx
  src/components/thumbnail/ThumbnailTitleHeader.tsx
  src/pages/Main.tsx
Labels: 💄 design

#16 Design#15 main/boxOffice
  src/App.tsx
  src/components/boxOffice/BoxOffice.tsx
  src/components/boxOffice/BoxOfficeArticle.tsx
  src/components/boxOffice/BoxOfficeHeader.tsx
  src/components/boxOffice/BoxOfficeWrapper.tsx
  src/components/boxOffice/BoxOfficeWrapperDescription.tsx
  src/core/boxOfficeMovies.ts
  src/pages/Main.tsx
Labels: 💄 design

#18 Design#17 main/collection
  src/App.tsx
  src/components/collection/Collection.tsx
  src/components/collection/CollectionArticle.tsx
  src/components/collection/CollectionHeader.tsx
  src/components/common/MovieArticle/MovieArticle.tsx
  src/components/common/MovieArticle/MovieInfo.tsx
  src/core/collectionImages.ts
  src/pages/Main.tsx
Labels: 💄 design

#20 Design#19 main/similar
  src/App.tsx
  src/components/similar/Similar.tsx
  src/components/similar/SimilarArticle.tsx
  src/components/similar/SimilarHeader.tsx
  src/core/similarWorks.ts
  src/pages/Main.tsx
Labels: 💄 design

#21 Design#9 animation/main section
  src/components/animation/AnimationHeader.tsx
  src/components/animation/AnimationMovies.tsx
  src/components/animation/AnimationTitleButtons.tsx
  src/components/animation/AnimationTitleDetail.tsx
  src/components/animation/AnimationTitleHeader.tsx
  src/components/animation/MoviesSection.tsx
  src/components/animation/MoviesSectionTitle.tsx
  src/core/animationMovies.ts
  src/pages/Animation.tsx
  src/styles/Layout/AnimationLayout.ts
  src/styles/common/commonText.ts
Labels: 💄 design

#25 Refactor#24 main/commonMovieArticle
  src/components/common/MovieArticle/MovieInfo.tsx
Labels: ♻️ refactor

#27 Design#26 main/cast
  src/App.tsx
  src/components/cast/Cast.tsx
  src/components/cast/CastArticle.tsx
  src/components/cast/CastHeader.tsx
  src/components/cast/CastInfo.tsx
  src/components/cast/CastSection.tsx
  src/components/common/Comment/CommentBottom.tsx
  src/components/layout/Main/MainContainer.ts
  src/core/castData.ts
  src/pages/Main.tsx
Labels: 💄 design

#29 Design#28 main/myPage
  src/App.tsx
  src/assets/image/body/bodyBargraphImg.png
  src/components/myPage/MyPageDescription.tsx
  src/components/myPage/MyPageHeader.tsx
  src/components/myPage/MyPagePopularComment.tsx
  src/components/myPage/MyPageReview.tsx
  src/components/myPage/MyPageSide.tsx
  src/components/myPage/PopularCommentBottom.tsx
  src/components/myPage/PopularCommentDetails.tsx
  src/components/myPage/PopularCommentHeader.tsx
  src/components/myPage/SetButton.tsx
  src/components/myPage/SetRates.tsx
  src/components/myPage/SetStars.tsx
  src/core/popularComments.ts
  src/pages/MyPage.tsx
  src/styles/Layout/MainContainer.ts
  src/styles/Layout/MyPageButtonContainer.ts
  src/styles/theme.ts
Labels: 💄 design

#33 Fix#32 stylelintrc.json
  .stylelintrc.json
Labels: 🐛 hotfix

#35 [ hotfix ] router오류 수정
  src/App.tsx
  src/Router.tsx
  src/pages/Main/Main.tsx
  src/pages/MyPage.tsx
Labels: 🐛 hotfix

#38 refactor#37 Main/MyPage
  src/components/myPage/MyPagePopularComment.tsx
  src/components/myPage/MyPageReview.tsx
  src/components/myPage/PopularCommentBottom.tsx
  src/components/myPage/PopularCommentDetails.tsx
  src/components/myPage/PopularCommentHeader.tsx
  src/components/myPage/SetButton.tsx
  src/components/myPage/SetRates.tsx
  src/components/myPage/SetStars.tsx
  src/pages/Main.tsx
  src/styles/Layout/MyPage/ButtonContainer.ts
  src/styles/Layout/MyPage/SetButtonBox.ts
  src/styles/common/myPage/ReviewBoxHeader.ts
  src/styles/common/myPage/SetRateContents.ts
  src/styles/common/myPage/SetTitle.ts
Labels: ♻️ refactor

#47 Refactor#46 main/commonMovieArticle
  src/components/collection/CollectionArticle.tsx
  src/components/common/MovieArticle/MovieArticle.tsx
  src/components/common/MovieArticle/MovieInfo.tsx
Labels: ♻️ refactor

#48 Design#45 comment/comment section
  src/components/comments/CommentSection.tsx
  src/components/comments/CommentToggle.tsx
  src/pages/Comment.tsx
Labels: 💄 design

#52 Refactor#49 animationpage
  src/components/animation/MovieSection/AnimationMovies.tsx
  src/components/animation/Title/AnimationTitleButtons.tsx
  src/components/animation/Title/AnimationTitleHeader.tsx
  src/components/common/MovieArticle/MovieArticle.tsx
  src/components/common/MovieArticle/MovieInfo.tsx
  src/core/Dummy.tsx
  src/core/animationMovies.ts
  src/pages/Animation.tsx
  src/styles/Layout/AnimationLayout.ts
Labels: ♻️ refactor

#53 Refactor#51 layoutsvg
  index.html
  src/assets/image/favicon.png
  src/components/common/Button/Button.tsx
  src/components/layout/Footer/FooterBottom/FooterBottomSecondRow.tsx
  src/components/layout/Footer/FooterTop.tsx
  src/components/layout/Header/HeaderLeft/HeaderLeft.tsx
  src/components/layout/Header/HeaderRight/HeaderInput.tsx
  src/components/layout/Header/HeaderRight/HeaderRight.tsx
Labels: 🐛 hotfix, ♻️ refactor

#64 Hotfix#63 all
  src/components/myPage/MyPageReview.tsx
  src/components/myPage/PopularCommentDetails.tsx
  src/components/myPage/PopularCommentHeader.tsx
  src/pages/Animation.tsx
  src/pages/Comment.tsx
  src/pages/MyPage.tsx
Labels: 🐛 hotfix

#58 refactor#55 myPageModal&Toggle
  src/components/myPage/SetButton.tsx
  src/styles/common/commonIcon.ts
  src/utils/MyPageModal.tsx
  src/utils/MyPageToggle.tsx
Labels: ♻️ refactor
